<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OXjPMJ0' shared service.

return $this->privates['.service_locator.OXjPMJ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminSystemController::Depot' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\AdminSystemController::admin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\AdminSystemController::ajoutComptB' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AdminSystemController::bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\AdminSystemController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController::admin' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
    'App\\Controller\\AdminSystemController:Depot' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\AdminSystemController:admin' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\AdminSystemController:ajoutComptB' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AdminSystemController:bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\AdminSystemController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController:admin' => ['privates', '.service_locator.9cYN13S', 'get_ServiceLocator_9cYN13SService.php', true],
], [
    'App\\Controller\\AdminSystemController::Depot' => '?',
    'App\\Controller\\AdminSystemController::admin' => '?',
    'App\\Controller\\AdminSystemController::ajoutComptB' => '?',
    'App\\Controller\\AdminSystemController::bloquerPartenaie' => '?',
    'App\\Controller\\AdminSystemController::setViewHandler' => '?',
    'App\\Controller\\UserController::admin' => '?',
    'App\\Controller\\AdminSystemController:Depot' => '?',
    'App\\Controller\\AdminSystemController:admin' => '?',
    'App\\Controller\\AdminSystemController:ajoutComptB' => '?',
    'App\\Controller\\AdminSystemController:bloquerPartenaie' => '?',
    'App\\Controller\\AdminSystemController:setViewHandler' => '?',
    'App\\Controller\\UserController:admin' => '?',
]);
