<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7tPqNtL' shared service.

return $this->privates['.service_locator.7tPqNtL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminSystemController::Depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AdminSystemController::admin' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\AdminSystemController::ajoutComptB' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AdminSystemController::bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\AdminSystemController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController::addUser' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UserController::allouerCompte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\AdminSystemController:Depot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AdminSystemController:admin' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\AdminSystemController:ajoutComptB' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\AdminSystemController:bloquerPartenaie' => ['privates', '.service_locator.V84UHq3', 'get_ServiceLocator_V84UHq3Service.php', true],
    'App\\Controller\\AdminSystemController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\UserController:addUser' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UserController:allouerCompte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
], [
    'App\\Controller\\AdminSystemController::Depot' => '?',
    'App\\Controller\\AdminSystemController::admin' => '?',
    'App\\Controller\\AdminSystemController::ajoutComptB' => '?',
    'App\\Controller\\AdminSystemController::bloquerPartenaie' => '?',
    'App\\Controller\\AdminSystemController::setViewHandler' => '?',
    'App\\Controller\\UserController::addUser' => '?',
    'App\\Controller\\UserController::allouerCompte' => '?',
    'App\\Controller\\AdminSystemController:Depot' => '?',
    'App\\Controller\\AdminSystemController:admin' => '?',
    'App\\Controller\\AdminSystemController:ajoutComptB' => '?',
    'App\\Controller\\AdminSystemController:bloquerPartenaie' => '?',
    'App\\Controller\\AdminSystemController:setViewHandler' => '?',
    'App\\Controller\\UserController:addUser' => '?',
    'App\\Controller\\UserController:allouerCompte' => '?',
]);
