<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElGuKXO\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElGuKXO/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerElGuKXO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerElGuKXO\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerElGuKXO\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'ElGuKXO',
    'container.build_id' => 'e9d55e57',
    'container.build_time' => 1565004625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerElGuKXO');
