<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoPCaET\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoPCaET/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXoPCaET.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXoPCaET\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerXoPCaET\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'XoPCaET',
    'container.build_id' => '5e89d722',
    'container.build_time' => 1565163050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoPCaET');
