<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCexYeO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCexYeO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRCexYeO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRCexYeO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRCexYeO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RCexYeO',
    'container.build_id' => 'e82905b5',
    'container.build_time' => 1566303276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRCexYeO');
