<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJLg54r\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJLg54r/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZJLg54r.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZJLg54r\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZJLg54r\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZJLg54r',
    'container.build_id' => '2b5c3999',
    'container.build_time' => 1564997937,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZJLg54r');
