<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8e1d6yi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8e1d6yi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8e1d6yi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8e1d6yi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8e1d6yi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8e1d6yi',
    'container.build_id' => '1bb702dc',
    'container.build_time' => 1565984582,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8e1d6yi');
